# Generated by Django 5.2.7 on 2025-10-24 09:12

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('description', models.TextField(blank=True, verbose_name='Course Description')),
                ('pargraph', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Faculty Name')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Course Type')),
                ('duration', models.PositiveSmallIntegerField(default=3, verbose_name='Default Duration (Years)')),
                ('application_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Default Application Fee')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardreg.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Course Type',
                'verbose_name_plural': 'Course Types',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Stream Name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardreg.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'unique_together': {('name', 'course')},
            },
        ),
        migrations.CreateModel(
            name='BoardRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255, verbose_name='Candidate Name')),
                ('father_name', models.CharField(max_length=255, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=255, verbose_name="Mother's Name")),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Photo')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('category', models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS')], max_length=10, verbose_name='Category')),
                ('id_proof_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('voter', 'Voter ID')], max_length=20, verbose_name='ID Proof Type')),
                ('id_proof_no', models.CharField(max_length=50, verbose_name='ID Proof Number')),
                ('aadhaar_front', models.FileField(upload_to='id_proofs/', verbose_name='Aadhaar Card Front')),
                ('aadhaar_back', models.FileField(upload_to='id_proofs/', verbose_name='Aadhaar Card Back')),
                ('employed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Are You Currently Employed?')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('father_contact', models.CharField(blank=True, max_length=15, verbose_name="Father's Contact Number")),
                ('mother_contact', models.CharField(blank=True, max_length=15, verbose_name="Mother's Contact Number")),
                ('country', models.CharField(choices=[('india', 'India'), ('other', 'Other')], max_length=10, verbose_name='Country')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('address', models.TextField(verbose_name='Address')),
                ('pincode', models.PositiveIntegerField(verbose_name='Pincode')),
                ('secondary_board', models.CharField(max_length=255, verbose_name='Secondary Board/University')),
                ('secondary_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Secondary Year of Passing')),
                ('secondary_percentage', models.CharField(max_length=10, verbose_name='Secondary Percentage/CGPA')),
                ('secondary_doc', models.FileField(upload_to='qualifications/', verbose_name='Secondary Document')),
                ('srsecondary_board', models.CharField(max_length=255, verbose_name='Sr. Secondary Board/University')),
                ('srsecondary_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Sr. Secondary Year of Passing')),
                ('srsecondary_percentage', models.CharField(max_length=10, verbose_name='Sr. Secondary Percentage/CGPA')),
                ('srsecondary_doc', models.FileField(upload_to='qualifications/', verbose_name='Sr. Secondary Document')),
                ('graduation_board', models.CharField(max_length=255, verbose_name='Graduation University')),
                ('graduation_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Graduation Year of Passing')),
                ('graduation_percentage', models.CharField(max_length=10, verbose_name='Graduation Percentage/CGPA')),
                ('graduation_doc', models.FileField(upload_to='qualifications/', verbose_name='Graduation Document')),
                ('postgraduation_board', models.CharField(blank=True, max_length=255, verbose_name='Post Graduation University')),
                ('postgraduation_year', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Post Graduation Year of Passing')),
                ('postgraduation_percentage', models.CharField(blank=True, max_length=10, verbose_name='Post Graduation Percentage/CGPA')),
                ('postgraduation_doc', models.FileField(blank=True, upload_to='qualifications/', verbose_name='Post Graduation Document')),
                ('other_board', models.CharField(blank=True, max_length=255, verbose_name='Other Board/University')),
                ('other_year', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Other Year of Passing')),
                ('other_percentage', models.CharField(blank=True, max_length=10, verbose_name='Other Percentage/CGPA')),
                ('other_doc', models.FileField(blank=True, upload_to='qualifications/', verbose_name='Other Document')),
                ('year', models.CharField(choices=[('1', '1th Year'), ('2', '2th Year'), ('3', '3th Year'), ('4', '4th Year'), ('5', '5th Year'), ('6', '6th Year')], max_length=10, verbose_name='Year')),
                ('month_session', models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=20, verbose_name='Month/Session')),
                ('session', models.CharField(choices=[('regular', 'Regular')], max_length=20, verbose_name='Session')),
                ('mode_of_study', models.CharField(choices=[('regular', 'Regular'), ('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('online', 'Online')], max_length=20, verbose_name='Mode of Study')),
                ('hostel_facility', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Hostel Facility Required?')),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Application Fee')),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration (Years)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardreg.course', verbose_name='Course')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardreg.coursetype', verbose_name='Course Type')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardreg.faculty', verbose_name='Faculty')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardreg.stream', verbose_name='Stream')),
            ],
            options={
                'verbose_name': 'Board Registration',
                'verbose_name_plural': 'Board Registrations',
            },
        ),
    ]
