# Generated by Django 5.2.7 on 2025-10-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boardreg.coursetype', verbose_name='Course Type'),
            preserve_default=False,
        ),
    ]
