# Generated by Django 6.0 on 2026-02-13 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0002_course_coursetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardregistration',
            name='graduation_board',
            field=models.CharField(blank=True, max_length=255, verbose_name='Graduation University'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='graduation_doc',
            field=models.FileField(blank=True, upload_to='qualifications/', verbose_name='Graduation Document'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='graduation_percentage',
            field=models.CharField(blank=True, max_length=10, verbose_name='Graduation Percentage/CGPA'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Graduation Year of Passing'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='srsecondary_board',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sr. Secondary Board/University'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='srsecondary_doc',
            field=models.FileField(blank=True, upload_to='qualifications/', verbose_name='Sr. Secondary Document'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='srsecondary_percentage',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sr. Secondary Percentage/CGPA'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='srsecondary_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Sr. Secondary Year of Passing'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='duration',
            field=models.CharField(default='3 Years', max_length=50, verbose_name='Default Duration'),
        ),
    ]
