# Generated by Django 6.0 on 2026-02-13 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0003_alter_boardregistration_graduation_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardregistration',
            name='graduation_board',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='graduation_doc',
            field=models.FileField(blank=True, null=True, upload_to='qualifications/'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='graduation_percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='other_board',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='other_doc',
            field=models.FileField(blank=True, null=True, upload_to='qualifications/'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='other_percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='other_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='postgraduation_board',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='postgraduation_doc',
            field=models.FileField(blank=True, null=True, upload_to='qualifications/'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='postgraduation_percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='postgraduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='secondary_board',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='secondary_doc',
            field=models.FileField(upload_to='qualifications/'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='secondary_percentage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='secondary_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='srsecondary_board',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='srsecondary_doc',
            field=models.FileField(blank=True, null=True, upload_to='qualifications/'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='srsecondary_percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='srsecondary_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Course Type'),
        ),
    ]
