# Generated by Django 6.0 on 2026-02-13 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0004_alter_boardregistration_graduation_board_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='CourseType',
            new_name='course_type',
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stream',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardreg.course'),
        ),
    ]
