# Generated by Django 6.0 on 2026-02-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0005_rename_coursetype_course_course_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetype',
            name='faculty',
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boardreg.faculty', verbose_name='Faculty'),
            preserve_default=False,
        ),
    ]
