# Generated by Django 6.0 on 2026-02-13 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0007_remove_course_faculty_coursetype_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetype',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='coursetype',
            name='faculty',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='3 Years', max_length=50, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardreg.faculty', verbose_name='Faculty'),
        ),
    ]
