# Generated by Django 6.0 on 2026-02-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0008_remove_coursetype_duration_remove_coursetype_faculty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardregistration',
            options={},
        ),
        migrations.RemoveField(
            model_name='boardregistration',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardreg.course'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardreg.coursetype'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardreg.stream'),
        ),
    ]
