# Generated by Django 6.0 on 2026-02-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0011_add_duration_session_mode_fks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardregistration',
            name='year',
        ),
    ]
