# Generated by Django 6.0 on 2026-03-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0012_remove_year_from_boardregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardregistration',
            name='internship_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Internship ID'),
        ),
        migrations.AddField(
            model_name='boardregistration',
            name='register_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Register No'),
        ),
    ]
