# Generated by Django 6.0 on 2026-03-12 04:32

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0013_boardregistration_internship_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardregistration',
            name='address',
        ),
        migrations.AddField(
            model_name='boardregistration',
            name='House_Building_Name_or_Number',
            field=models.TextField(blank=True, default='', verbose_name='House/Building Name or Number'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='boardregistration',
            name='State',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='State'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='boardregistration',
            name='Street_Name',
            field=models.TextField(blank=True, default='', verbose_name='Street / Area Name /Locality Name'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='boardregistration',
            name='date_of_join',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Join'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='boardregistration',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='District'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='boardregistration',
            name='post_office_name',
            field=models.TextField(blank=True, default='', verbose_name='Post Office Name'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='boardregistration',
            name='village_town_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Village / Town / City'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
    ]
