# Generated by Django 6.0 on 2026-03-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0014_remove_boardregistration_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardregistration',
            name='House_Building_Name_or_Number',
            field=models.TextField(verbose_name='House/Building Name or Number'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='State',
            field=models.CharField(max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='Street_Name',
            field=models.TextField(verbose_name='Street / Area Name /Locality Name'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='date_of_join',
            field=models.DateField(verbose_name='Date of Join'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='district',
            field=models.CharField(max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='post_office_name',
            field=models.TextField(verbose_name='Post Office Name'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='village_town_city',
            field=models.CharField(max_length=100, verbose_name='Village / Town / City'),
        ),
    ]
