# Generated by Django 6.0 on 2026-03-12 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0015_alter_boardregistration_house_building_name_or_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardregistration',
            name='academic_delivery_end',
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 0, 0), verbose_name='Academic Delivery End'),
            preserve_default=False,
        ),
    ]
