# Generated by Django 6.0 on 2026-03-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardreg', '0017_branch_boardregistration_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardregistration',
            name='internship_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Internship ID'),
        ),
        migrations.AlterField(
            model_name='boardregistration',
            name='register_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Register No'),
        ),
    ]
